# Generated by Django 6.0.4 on 2026-04-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
