# Generated by Django 6.0.5 on 2026-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensagem',
            field=models.TextField(max_length=1500),
        ),
    ]
